FROM python:3.6.4


# install environment dependencies
RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
    netcat \
    && apt-get -q clean



# set working directory
RUN mkdir -p .usr/src/app
WORKDIR /usr/src/app


# add requirements file
COPY ./requirements.txt /usr/src/app/requirements.txt


# Install requirements
RUN pip install -r requirements.txt



# add app
COPY . /usr/src/app

# run the server
#CMD python manage.py run -h 0.0.0.0
CMD gunicorn --workers=3 -b 0.0.0.0:5000 --log-level=debug manage:app 


